### ISSUE TITLE
Build fails --without-guile

### ISSUE THREAD

**Issue by postmasters** [stevengj/libctl#28]
After `configure --without-guile`, a `make` will fail in `utils`. Perhaps Guile is a required dependency after all?

**Comment by postmasters** [comment]
By the way, this is a fresh clone, and after `autogen.sh`.

**Comment by stevengj** [comment]
If you use the release tarball (libctl-4.1.3.tar.gz in https://github.com/stevengj/libctl/releases), it does not require guile.

If you build from git source, you need guile because it is used to generate the `geom-ctl-io.c` file, which is needed to build libctlgeom.   However this file is included in the release tarball.

Essentially, guile is only needed in `--enable-maintainer-mode` for regenerating the source.
